backbone: dgcnn
data_aug: true
data_path: /home/jchen152/workspace/Data/modelnet40_fs/modelnet40_ply_hdf5_2048_fs
decay_ep: 5
device: cuda
epochs: 80
exp_name: dgcnn_cia_5s_15q
fs_head: cia
gamma: 0.7
k_way: 5
lr: 0.0008
lr_sch: true
n_shot: 5
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 15
seed: 0
train: true
