backbone: dgcnn
data_aug: true
data_path: /home/jchen152/workspace/Data/modelnet40_fs_crossvalidation
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ModelNet40_cross
exp_name: ProtoNet_5k5s15q_fold2
fold: 2
fs_head: protonet
gamma: 0.7
k_way: 5
lr: 0.0008
lr_sch: true
multigpu: false
n_shot: 5
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 15
seed: 0
train: true
