backbone: mymodel
data_aug: true
data_path: /home/jchen152/workspace/Data/ScanObjectNN_fs_crossvalidation/Data
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ScanObjectNN_cross
exp_name: Mymodel_5k1s10q_fold1
fold: 1
fs_head: trip
gamma: 0.7
k_way: 5
lr: 0.0001
lr_sch: false
n_shot: 1
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 10
seed: 0
train: true
