backbone: mymodel
data_aug: true
data_path: /home/jchen152/workspace/Data/modelnet40_fs_crossvalidation
decay_ep: 5
device: cuda
epochs: 80
exp_folder_name: ModelNet40_cross
exp_name: Mymodel_5k5s10q_tipcia_fold0_pair
fold: 0
fs_head: Trip_CIA
gamma: 0.7
k_way: 5
lr: 0.0001
lr_sch: false
multigpu: false
n_shot: 5
project_path: /home/jchen152/workspace/Few_Shot_Point_Cloud
query: 10
seed: 0
train: true
